### ISSUE TITLE
Pillars at the edge of view distance

### ISSUE THREAD

**Issue by idoash4** [Civcraft/random-spawn#5]
Local testing confirmed that random-spawn is causing the problem. Removing random-spawn will remove the pillars. Any idea on why random-spawn is fucking around with the world generation?

**Comment by idoash4** [comment]
https://github.com/Civcraft/random-spawn/blob/master/src/main/java/me/josvth/randomspawn/RandomSpawn.java#L245 The problem is with this for loop. Any objections to commenting out this part?

**Comment by ttk2** [comment]
none at all, but how is it messing with chunk processing, that's just stupid.

**Comment by idoash4** [comment]
From my understanding it is supposed to make sure the client load the blocks where the player spawned. There is probably a good reason why sendBlockChange() is deprecated.

**Comment by ttk2** [comment]
cool make a pull, jenkins will compile it.

**Comment by idoash4** [comment]
https://github.com/Civcraft/random-spawn/pull/6

**Comment by ProgrammerDan** [comment]
Looks like this is fixed, yes? Closing. If not, reopen.
